# Generated by Django 3.2 on 2021-04-25 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percel_type', models.CharField(choices=[('Fragile', 'Fragile'), ('Liquid', 'Liquid')], max_length=50)),
                ('merchant_id', models.CharField(max_length=50)),
                ('order_place', models.CharField(choices=[('ID', 'Inside of Dhaka'), ('DD', 'Division of Dhaka'), ('OD', 'Outside of Dhaka')], max_length=50)),
                ('weight', models.CharField(choices=[('wa', '500 gm to 2 kg'), ('wb', '3 kg'), ('wc', '4 kg'), ('wd', '5 kg')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
