# Generated by Django 3.2 on 2021-04-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courierapp', '0003_alter_parcel_order_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='order_place',
            field=models.CharField(choices=[('i_d', 'Inside of Dhaka'), ('d_d', 'Division of Dhaka'), ('o_d', 'Outside of Dhaka')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='percel_type',
            field=models.CharField(choices=[('fragile', 'Fragile'), ('liquid', 'Liquid')], max_length=50),
        ),
    ]
